#Requires -RunAsAdministrator

Write-Host "Download mpm.exe..." -ForegroundColor Cyan
Invoke-WebRequest -Uri "https://www.mathworks.com/mpm/win64/mpm" -OutFile "mpm.exe"

# Проверяем, что файл скачался
if (-not (Test-Path "mpm.exe")) {
    Write-Error "Failed to dowload mpm.exe"
    exit 1
}

# Задаём путь до установленного матлаба
$installPath = "C:\Program Files\MATLAB\R2024b"

# Проверяем, что папка существует
if (-not (Test-Path $installPath)) {
    Write-Error "Matlab folder install not found!: $installPath"
    exit 1
}



.\mpm.exe install --release=R2024b --destination="$installPath" --products=5G_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=AUTOSAR_Blockset
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Aerospace_Blockset
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Aerospace_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Antenna_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Audio_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Automated_Driving_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Bioinformatics_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Bluetooth_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=C2000_Microcontroller_Blockset
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Communications_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Control_System_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Curve_Fitting_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=DDS_Blockset
.\mpm.exe install --release=R2024b --destination="$installPath" --products=DSP_HDL_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=DSP_System_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Data_Acquisition_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Database_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Datafeed_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_HDL_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Econometrics_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Embedded_Coder
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Financial_Instruments_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Financial_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Fixed-Point_Designer
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Fuzzy_Logic_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=GPU_Coder
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Global_Optimization_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=HDL_Coder
.\mpm.exe install --release=R2024b --destination="$installPath" --products=HDL_Verifier
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Image_Acquisition_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Image_Processing_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Industrial_Communication_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Instrument_Control_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=LTE_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Lidar_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Coder
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Compiler
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Compiler_SDK
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Parallel_Server
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Production_Server
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Report_Generator
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Test
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Web_App_Server
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Mapping_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Medical_Imaging_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Mixed-Signal_Blockset
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Model_Predictive_Control_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Model-Based_Calibration_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Motor_Control_Blockset
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Navigation_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Optimization_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Parallel_Computing_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Partial_Differential_Equation_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Phased_Array_System_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Polyspace_Bug_Finder
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Polyspace_Bug_Finder_Server
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Polyspace_Code_Prover
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Polyspace_Code_Prover_Server
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Polyspace_Test
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Powertrain_Blockset
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Predictive_Maintenance_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=RF_Blockset
.\mpm.exe install --release=R2024b --destination="$installPath" --products=RF_PCB_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=RF_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=ROS_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Radar_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Reinforcement_Learning_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Requirements_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Risk_Management_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Robotics_System_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Robust_Control_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Satellite_Communications_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Sensor_Fusion_and_Tracking_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=SerDes_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Signal_Integrity_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Signal_Processing_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=SimBiology
.\mpm.exe install --release=R2024b --destination="$installPath" --products=SimEvents
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simscape
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simscape_Battery
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simscape_Driveline
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simscape_Electrical
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simscape_Fluids
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simscape_Multibody
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_3D_Animation
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Check
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Coder
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Compiler
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Control_Design
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Coverage
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Design_Optimization
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Design_Verifier
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Desktop_Real-Time
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Fault_Analyzer
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_PLC_Coder
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Real-Time
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Report_Generator
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Test
.\mpm.exe install --release=R2024b --destination="$installPath" --products=SoC_Blockset
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Spreadsheet_Link
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Stateflow
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Statistics_and_Machine_Learning_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Symbolic_Math_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=System_Composer
.\mpm.exe install --release=R2024b --destination="$installPath" --products=System_Identification_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Text_Analytics_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=UAV_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Vehicle_Dynamics_Blockset
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Vehicle_Network_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Vision_HDL_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=WLAN_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Wavelet_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Wireless_HDL_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Wireless_Testbench



.\mpm.exe install --release=R2024b --destination="$installPath" --products=6G_Exploration_Library_for_5G_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=ASIC_Testbench_for_HDL_Verifier
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Aerospace_Blockset_Interface_for_Unreal_Engine_Projects
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Audio_Toolbox_Interface_for_SpeechBrain_and_Torchaudio_Libraries
.\mpm.exe install --release=R2024b --destination="$installPath" --products="Automated_Driving_Toolbox_Importer_for_Zenrin_Japan_Map_API_3.0_(Itsumo_NAVI_API_3.0)_Service"
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Automated_Driving_Toolbox_Interface_for_Unreal_Engine_Projects
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Automated_Driving_Toolbox_Model_for_Lidar_Lane_Detection
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Automated_Driving_Toolbox_Test_Suite_for_Euro_NCAP_Protocols
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Automated_Visual_Inspection_Library_for_Computer_Vision_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=CI/CD_Automation_for_Simulink_Check
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Communications_Toolbox_Support_Package_for_Analog_Devices_ADALM-Pluto_Radio
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Communications_Toolbox_Support_Package_for_RTL-SDR_Radio
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Communications_Toolbox_Support_Package_for_USRP_Embedded_Series_Radio
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Communications_Toolbox_Support_Package_for_USRP_Radio
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Communications_Toolbox_Wireless_Network_Simulation_Library
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Component_Deployment_Guideline_for_Embedded_Coder
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Interface_for_OpenCV_in_MATLAB
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Interface_for_OpenCV_in_Simulink
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Model_for_BiSeNet_v2_Semantic_Segmentation_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Model_for_Inflated-3D_Video_Classification
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Model_for_Mask_R-CNN_Instance_Segmentation
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Model_for_Object_Keypoint_Detection
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Model_for_Pose_Mask_R-CNN_6-DoF_Object_Pose_Estimation
.\mpm.exe install --release=R2024b --destination="$installPath" --products="Computer_Vision_Toolbox_Model_for_R(2+1)D_Video_Classification"
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Model_for_RAFT_Optical_Flow_Estimation
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Model_for_RTMDet_Object_Detection
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Model_for_RetinaFace_Face_Detection
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Model_for_SOLOv2_Instance_Segmentation
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Model_for_SlowFast_Video_Classification
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Model_for_Text_Detection
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Model_for_Vision_Transformer_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Model_for_YOLO_v2_Object_Detection
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Model_for_YOLO_v3_Object_Detection
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_Model_for_YOLO_v4_Object_Detection
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Computer_Vision_Toolbox_OCR_Language_Data
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Data_Acquisition_Toolbox_Support_Package_for_Analog_Devices_ADALM1000_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Data_Acquisition_Toolbox_Support_Package_for_Digilent_Analog_Discovery_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Data_Acquisition_Toolbox_Support_Package_for_Measurement_Computing_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Data_Acquisition_Toolbox_Support_Package_for_National_Instruments_NI-DAQmx_Devices
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Data_Acquisition_Toolbox_Support_Package_for_Windows_Sound_Cards
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Database_Toolbox_Interface_for_Neo4j_Bolt_Protocol
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Databricks_ODBC_Driver_for_Database_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_HDL_Toolbox_Support_Package_for_AMD_FPGA_and_SoC_Devices
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_HDL_Toolbox_Support_Package_for_Intel_FPGA_and_SoC_Devices
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Converter_for_ONNX_Model_Format
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Converter_for_PyTorch_Model_Format
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Converter_for_TensorFlow_models
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Importer_for_Caffe_Models
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Interface_for_TensorFlow_Lite
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_Compression_Library
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_AlexNet_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_DarkNet-19_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_DarkNet-53_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_DenseNet-201_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_EfficientNet-b0_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_GoogLeNet_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_Inception-ResNet-v2_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_Inception-v3_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_MobileNet-v2_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_NASNet-Large_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_NASNet-Mobile_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_Places365-GoogLeNet_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_ResNet-101_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_ResNet-18_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_ResNet-50_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_ShuffleNet_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_VGG-16_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_VGG-19_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Model_for_Xception_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Deep_Learning_Toolbox_Verification_Library
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Embedded_Coder_Interface_to_QEMU_Emulator
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Embedded_Coder_Support_Package_For_Linux_Applications
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Embedded_Coder_Support_Package_for_AMD_SoC_Devices
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Embedded_Coder_Support_Package_for_ARM_Cortex-A_Processors
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Embedded_Coder_Support_Package_for_ARM_Cortex-M_Processors
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Embedded_Coder_Support_Package_for_ARM_Cortex-R_Processors
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Embedded_Coder_Support_Package_for_BeagleBone_Black_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Embedded_Coder_Support_Package_for_Infineon_AURIX_TC3x_Microcontrollers
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Embedded_Coder_Support_Package_for_Infineon_AURIX_TC4x_Microcontrollers
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Embedded_Coder_Support_Package_for_Intel_SoC_Devices
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Embedded_Coder_Support_Package_for_Qualcomm_Hexagon_Processors
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Embedded_Coder_Support_Package_for_STMicroelectronics_STM32_Processors
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Ephemeris_Data_for_Aerospace_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Extended_Tire_Features_for_Vehicle_Dynamics_Blockset
.\mpm.exe install --release=R2024b --destination="$installPath" --products=FMU_Builder_For_Simulink
.\mpm.exe install --release=R2024b --destination="$installPath" --products=GPU_Coder_Interface_for_Deep_Learning_Libraries
.\mpm.exe install --release=R2024b --destination="$installPath" --products=GUIDE_to_App_Designer_Migration_Tool_for_MATLAB
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Geoid_Data_for_Aerospace_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=HDL_Coder_Support_Package_for_AMD_FPGA_and_SoC_Devices
.\mpm.exe install --release=R2024b --destination="$installPath" --products=HDL_Coder_Support_Package_for_Intel_FPGA_and_SoC_Devices
.\mpm.exe install --release=R2024b --destination="$installPath" --products=HDL_Coder_Support_Package_for_Microchip_FPGA_and_SoC_Devices
.\mpm.exe install --release=R2024b --destination="$installPath" --products=HDL_Verifier_Support_Package_for_AMD_FPGA_and_SoC_Devices
.\mpm.exe install --release=R2024b --destination="$installPath" --products=HDL_Verifier_Support_Package_for_Intel_FPGA_Boards
.\mpm.exe install --release=R2024b --destination="$installPath" --products=HDL_Verifier_Support_Package_for_Microsemi_FPGA_Boards
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Hyperspectral_Imaging_Library_for_Image_Processing_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Image_Acquisition_Toolbox_Support_Package_for_DCAM_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Image_Acquisition_Toolbox_Support_Package_for_Kinect_for_Windows_Sensor
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Image_Acquisition_Toolbox_Support_Package_for_Matrox_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Image_Acquisition_Toolbox_Support_Package_for_National_Instruments_Frame_Grabbers
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Image_Acquisition_Toolbox_Support_Package_for_OS_Generic_Video_Interface
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Image_Acquisition_Toolbox_Support_Package_for_Point_Grey_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Image_Acquisition_Toolbox_Support_Package_for_Teledyne_DALSA_Sapera_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Image_Processing_Toolbox_Image_Data
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Image_Processing_Toolbox_Model_for_Segment_Anything_Model
.\mpm.exe install --release=R2024b --destination="$installPath" --products="Instrument_Control_Toolbox_Support_Package_for_Keysight_(Agilent)_IO_Libraries_and_VISA_Interface"
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Instrument_Control_Toolbox_Support_Package_for_National_Instruments_NI-845x_I2C/SPI_Interface
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Instrument_Control_Toolbox_Support_Package_for_National_Instruments_NI-DCPower_Power_Supplies
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Instrument_Control_Toolbox_Support_Package_for_National_Instruments_NI-DMM_Digital_Multimeters
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Instrument_Control_Toolbox_Support_Package_for_National_Instruments_NI-FGEN_Function_Generators
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Instrument_Control_Toolbox_Support_Package_for_National_Instruments_NI-SCOPE_Oscilloscopes
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Instrument_Control_Toolbox_Support_Package_for_National_Instruments_NI-SWITCH_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Instrument_Control_Toolbox_Support_Package_for_National_Instruments_VISA_and_ICP_Interfaces
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Instrument_Control_Toolbox_Support_Package_for_Rohde_Schwarz_VISA_Interface
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Instrument_Control_Toolbox_Support_Package_for_Total_Phase_Aardvark_I2C/SPI_Interface
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Integro-Differential_Modeling_Framework_for_MATLAB
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Large-Scale_Cloud_Simulation_for_Simulink
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Lidar_Toolbox_Interface_for_OpenPCDet_Library
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Lidar_Toolbox_Model_for_PointNet++_Classification
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Lidar_Toolbox_Model_for_RandLA-Net_Semantic_Segmentation
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Lidar_Toolbox_Support_Package_for_Hokuyo_LiDAR_Sensors
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Lidar_Toolbox_Support_Package_for_Ouster_Lidar_Sensors
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Lidar_Toolbox_Support_Package_for_Velodyne_LiDAR_Sensors
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Basemap_Data_-_bluegreen
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Basemap_Data_-_colorterrain
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Basemap_Data_-_grayland
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Basemap_Data_-_grayterrain
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Basemap_Data_-_landcover
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Client_for_MATLAB_Production_Server
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Coder_Interface_for_Deep_Learning_Libraries
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Coder_Interface_for_Visual_Studio_Code_Debugging
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Coder_Support_Package_for_NVIDIA_Jetson_and_NVIDIA_DRIVE_Platforms
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Support_Package_for_Android_Sensors
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Support_Package_for_Apple_iOS_Sensors
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Support_Package_for_Arduino_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Support_Package_for_BeagleBone_Black_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Support_Package_for_LEGO_MINDSTORMS_EV3_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Support_Package_for_Quantum_Computing
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Support_Package_for_Raspberry_Pi_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Support_Package_for_USB_Webcams
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Support_for_HEIF/HEIC_Image_Format
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MATLAB_Support_for_MinGW-w64_C/C++/Fortran_Compiler
.\mpm.exe install --release=R2024b --destination="$installPath" --products="Machine_Learning_Pipelines_for_Statistics_and_Machine_Learning_Toolbox_(Beta)"
.\mpm.exe install --release=R2024b --destination="$installPath" --products=MariaDB_ODBC_Driver_for_Database_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Medical_Imaging_Toolbox_Interface_for_Cellpose
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Medical_Imaging_Toolbox_Interface_for_MONAI_Label_Library
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Medical_Imaging_Toolbox_Model_for_Medical_Segment_Anything_Model
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Mixed-Signal_Blockset_Models
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Modelscape_for_MATLAB
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Multi-Version_Co-Simulation_for_Simulink
.\mpm.exe install --release=R2024b --destination="$installPath" --products=PostgreSQL_ODBC_Driver_for_Database_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Powertrain_Blockset_Drive_Cycle_Data
.\mpm.exe install --release=R2024b --destination="$installPath" --products=RF_Blockset_Models_for_Analog_Devices_RF_Transceivers
.\mpm.exe install --release=R2024b --destination="$installPath" --products=ROS_Toolbox_Support_Package_for_TurtleBot-Based_Robots
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Radar_Toolbox_Support_Package_for_Texas_Instruments_mmWave_Radar_Sensors
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Robotics_System_Toolbox_Interface_for_Unreal_Engine_Projects
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Robotics_System_Toolbox_Offroad_Autonomy_Library
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Robotics_System_Toolbox_Robot_Library_Data
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Robotics_System_Toolbox_Support_Package_for_Kinova_Gen3_Manipulators
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Robotics_System_Toolbox_Support_Package_for_Universal_Robots_UR_Series_Manipulators
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Scenario_Builder_for_Automated_Driving_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Signal_Processing_Toolbox_Support_Package_for_Linux_IIO_Devices
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_3D_Animation_Interface_for_Unreal_Engine_Projects
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Coder_Support_Package_for_ARM_Cortex-based_VEX_Microcontroller
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Coder_Support_Package_for_BeagleBone_Blue_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Coder_Support_Package_for_NXP_FRDM-K64F_Board
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Coder_Support_Package_for_NXP_FRDM-KL25Z_Board
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Coder_Support_Package_for_STMicroelectronics_Nucleo_Boards
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Coder_Support_Package_for_VEX_EDR_V5_Robot_Brain
.\mpm.exe install --release=R2024b --destination="$installPath" --products="Simulink_Interface_for_Siemens_MF-Tyre/MF-Swift_Tire_Model"
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Real-Time_XIL_Support_Package
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Support_Package_for_Android_Devices
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Support_Package_for_Arduino_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Support_Package_for_LEGO_MINDSTORMS_EV3_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Support_Package_for_Parrot_Minidrones
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Support_Package_for_Raspberry_Pi_Hardware
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Simulink_Test_Support_Package_for_ASAM_XIL
.\mpm.exe install --release=R2024b --destination="$installPath" --products=SoC_Blockset_Support_Package_for_AMD_FPGA_and_SoC_Devices
.\mpm.exe install --release=R2024b --destination="$installPath" --products=SoC_Blockset_Support_Package_for_Embedded_Linux_Devices
.\mpm.exe install --release=R2024b --destination="$installPath" --products=SoC_Blockset_Support_Package_for_Intel_Devices
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Streaming_Data_Framework_for_MATLAB_Production_Server
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Text_Analytics_Toolbox_Model_for_BERT-Base_Multilingual_Cased_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Text_Analytics_Toolbox_Model_for_BERT-Base_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Text_Analytics_Toolbox_Model_for_BERT-Large_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Text_Analytics_Toolbox_Model_for_BERT-Mini_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Text_Analytics_Toolbox_Model_for_BERT-Small_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Text_Analytics_Toolbox_Model_for_BERT-Tiny_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Text_Analytics_Toolbox_Model_for_all-MiniLM-L12-v2_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Text_Analytics_Toolbox_Model_for_all-MiniLM-L6-v2_Network
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Text_Analytics_Toolbox_Model_for_fastText_English_16_Billion_Token_Word_Embedding
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Text_Analytics_Toolbox_Model_from_UDify_Data
.\mpm.exe install --release=R2024b --destination="$installPath" --products=UAV_Toolbox_Interface_for_Unreal_Engine_Projects
.\mpm.exe install --release=R2024b --destination="$installPath" --products=UAV_Toolbox_Support_Package_for_PX4_Autopilots
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Variant_Manager_for_Simulink
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Vehicle_Dynamics_Blockset_Interface_for_Unreal_Engine_Projects
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Vehicle_Dynamics_Blockset_Maneuver_Data
.\mpm.exe install --release=R2024b --destination="$installPath" --products=WINNER_II_Channel_Model_for_Communications_Toolbox
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Wireless_Testbench_Support_Package_for_NI_USRP_Radios


rem ########################################################################
rem ## OPTIONAL FEATURES
rem ########################################################################
rem ##
rem ## Uncomment the lines for the optional features you want to install or download.

.\mpm.exe install --release=R2024b --destination="$installPath" --products=Airport_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Construction_Site_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Curved_Road_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Double_Lane_Change_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Empty_Grass_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Empty_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Large_Parking_Lot_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Offroad_Pit_Mining_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Open_Surface_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Parking_Lot_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Straight_Road_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Suburban_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=TensorRT_Library
.\mpm.exe install --release=R2024b --destination="$installPath" --products=US_City_Block_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=US_Highway_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=Virtual_MCity_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=ZalaZONE_Automotive_Proving_Ground_High-speed_Handling_Course_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=ZalaZONE_Automotive_Proving_Ground_Hill_Tracks_Scene
.\mpm.exe install --release=R2024b --destination="$installPath" --products=ZalaZONE_Automotive_Proving_Ground_Smart_City_Scene

